name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile XeLaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode
      
      - name: Cat log
        if: failure()
        run: cat thesis.log && ls -la
