name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile XeLaTeX document - 1
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Run bibtex
        run: bibtex thesis.tex

      - name: Compile XeLaTeX document - 2
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Compile XeLaTeX document - 3
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Rename PDF
        run: mv thesis.pdf BP_Dan_Balarin.pdf

      - name: DEBUG list
        run: ls -la
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          files: BP_Dan_Balarin.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
