name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile XeLaTeX document - 1
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Run bibtex
        run: bibtex thesis.tex
        if: startsWith(github.ref, 'refs/tags/')

      - name: Compile XeLaTeX document - 2
        uses: xu-cheng/latex-action@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          root_file: thesis.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Compile XeLaTeX document - 3
        uses: xu-cheng/latex-action@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          root_file: thesis.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Rename PDF
        run: mv main.pdf BP_Dan_Balarin.pdf
        if: startsWith(github.ref, 'refs/tags/')

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: BP_Dan_Balarin.pdf
